version: "3.0"
services:
  quizzapp:
    image: hongsea/koompi-fifi:0.1.0
    ports:
      - "5000:5000"
    volumes:
      - ./:/var/www/app/
    working_dir: /var/www/app/
    command:
      - "./run.sh"
