version: "3.0"
services:
  koompififi_dev:
    image: node
    container_name: api-hotspot-dev
    restart: always
    ports:
      - "5002:5000"
    volumes:
      - "${HOTSPOT_PATH}:/var/www/app/"
    working_dir: /var/www/app/
    command:
      - "./start.sh"
